collections.types.Item({ id: 'formula', group: 'Advanced', name: 'Formula', icon: 'function', description: 'Computed from other fields.' });
collections.types.Item({ id: 'ai', group: 'Advanced', name: 'AI Generated', icon: 'auto_awesome', description: 'Generated by AI from a prompt.' });
